### ISSUE TITLE
Commission is in Addition to Price

### ISSUE THREAD

**Issue by mudgen** [nascarsid/Boolien-Smart-Contracts#10]
In past markeplaces I have reviewed the commissions/fees have been included in the asking price.  In the `buyItem` function the commission is in addition to the asking price. This may not be expected by buyers and sellers.

```Solidity
            // checking if the value includes commission.
            require(
                msg.value >=
                    ((itemsForSale[_id].askingPrice) * (1000 + commission)) /
                        1000,
                "Not enough funds sent, Please include commission"
            );
```

**Comment by akshaydevh** [comment]
This logic is added as per booleans requirement to impose commission overhead on the buyer instead of the seller. However, now it's planned to impose the commission on the seller.
