### ISSUE TITLE
WALLET could be a constant or immutable value

### ISSUE THREAD

**Issue by mudgen** [nascarsid/Boolien-Smart-Contracts#5]
The WALLET state variable could be made a constant or immutable variable because there is no function to change it once it is set. Doing so would reduce gas cost in the `finalizeBid` function.

**Comment by akshaydevh** [comment]
Boolean requires a function to update the WALLET address, hence adding a new function to update WALLET instead.

**Comment by mudgen** [comment]
Cool, makes sense.
